export { About } from './About';
export { Education } from './Education';
export { Experience } from './Experience';
export { Footer } from './Footer';
export { Header } from './Header';
export { Intro } from './Intro';
export { Section } from './Section';
export { ScrollProgress } from './ScrollProgress';
export { Skills } from './Skills';
